name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Extract and Build
      run: |
        unzip my_app_source.zip -d app_source
        cd app_source/my_app_source
        flutter pub get
        flutter build apk
