name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Extract and Build
      run: |
        unzip my_app_source.zip -d app_source
        cd app_source/my_app_source
        flutter pub get
        flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app_source/my_app_source/build/app/outputs/flutter-apk/app-release.apk
